name: lapor_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies: 
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.0.4
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.3
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_database: ^10.0.4
  fl_chart: ^0.55.2
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  get_cli: ^1.8.1
  google: ^0.0.1
  google_sign_in: ^5.4.2
  icon_forest: ^1.1.8
  image_picker: 0.8.6
  intl: ^0.17.0
  permission_handler: ^10.1.0
  syncfusion_flutter_charts: ^20.3.52
  lottie: 2.0.0
  firebase_storage: 11.0.6
  url_launcher: 6.1.7
  uuid: 3.0.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/LaporTrans.png
    - assets/LogoKominfoTanpaTeks.png
    - assets/logolaporpky.png
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/lottie/register.json
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: fonts/Montserrat-Regular.ttf
  uses-material-design: true

